"""Generate Python access component code from tool definitions."""
import re
from datetime import date

_IDENTIFIER_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')


def _safe_id(name: str) -> str:
    if not _IDENTIFIER_RE.match(name):
        raise ValueError(f"無効なテーブル/カラム名: {name!r}")
    return name


def _build_filter_meta(filterable_cols):
    meta = {}
    for col in filterable_cols:
        ops_str = col.get("allow_operators", "=") or "="
        ops = [op.strip() for op in ops_str.split(",") if op.strip()]
        meta[col["column_name"]] = {
            "allow_like":  bool(col.get("allow_like",  1)),
            "allow_array": bool(col.get("allow_array", 1)),
            "allow_operators": ops,
        }
    return meta


def generate(func, db_path="./data/sample.db"):
    columns         = func.get("columns", [])
    filterable_cols = [c for c in columns if c["is_filterable"]]
    filterable      = [c["column_name"] for c in filterable_cols]
    selectable      = [c["column_name"] for c in columns if c["is_selectable"]]

    fn_name       = _safe_id(func["name"])
    table         = _safe_id(func["target_table"])
    limit_default = func.get("limit_default", 100)
    description   = func["description"]
    examples      = [e.strip() for e in func.get("usage_examples", "").splitlines() if e.strip()]
    docstring_lines = [description]
    if examples:
        docstring_lines += ["", "使用例:"] + [f"    - {e}" for e in examples]

    docstring        = "\n    ".join(docstring_lines)
    filterable_repr  = repr(filterable)
    selectable_repr  = repr(selectable)
    filter_meta_repr = repr(_build_filter_meta(filterable_cols))
    today            = date.today().isoformat()

    code = f'''\
# Auto-generated by DB Access Component Generator
# Function: {fn_name}
# Target table: {table}
# Generated: {today}

import sqlite3
from typing import Optional

DB_PATH = "{db_path}"

FILTERABLE_COLUMNS_{fn_name} = {filterable_repr}
SELECTABLE_COLUMNS_{fn_name} = {selectable_repr}
FILTER_META_{fn_name} = {filter_meta_repr}


def {fn_name}(
    query_type: str = "rows",
    select_items: Optional[list] = None,
    filters: Optional[dict] = None,
    limit: int = {limit_default},
) -> list[dict]:
    """
    {docstring}
    """
    where_parts, params = [], []
    if filters:
        _valid_ops = {{"=", "<=", "<", ">=", ">", "!="}}
        for col, val in filters.items():
            if col not in FILTERABLE_COLUMNS_{fn_name}:
                continue
            meta        = FILTER_META_{fn_name}.get(col, {{}})
            allow_like  = meta.get("allow_like",  True)
            allow_array = meta.get("allow_array", True)
            allowed_ops = set(meta.get("allow_operators", ["="]))
            if isinstance(val, list) and allow_array:
                where_parts.append(f"{{col}} IN ({{','.join('?' * len(val))}})")
                params.extend(val)
            elif isinstance(val, dict) and "op" in val:
                op = val.get("op", "=")
                v  = val.get("value")
                if op in _valid_ops and op in allowed_ops:
                    where_parts.append(f"{{col}} {{op}} ?")
                    params.append(v)
            elif isinstance(val, str) and allow_like and ("%" in val or "_" in val):
                where_parts.append(f"{{col}} LIKE ?")
                params.append(val)
            elif "=" in allowed_ops:
                where_parts.append(f"{{col}} = ?")
                params.append(val)

    where = ("WHERE " + " AND ".join(where_parts)) if where_parts else ""

    if query_type == "count":
        sql = f"SELECT COUNT(*) FROM {table} {{where}}".strip()
    else:
        if not select_items:
            select_items = list(SELECTABLE_COLUMNS_{fn_name})
        select_clause = ", ".join(
            item for item in select_items if item in SELECTABLE_COLUMNS_{fn_name}
        ) or "*"
        sql = f"SELECT DISTINCT {{select_clause}} FROM {table} {{where}} LIMIT ?".strip()
        params.append(limit)

    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        return [dict(r) for r in conn.execute(sql, params).fetchall()]
'''
    return code


def generate_all(funcs, db_path="./data/sample.db"):
    parts = [
        "# Auto-generated by DB Access Component Generator\n"
        "import sqlite3\n"
        "from typing import Optional\n"
        f'\nDB_PATH = "{db_path}"\n'
    ]
    for func in funcs:
        block = generate(func, db_path)
        lines = block.splitlines()
        start = next(
            (i for i, l in enumerate(lines) if l.startswith("FILTERABLE_")), 0
        )
        parts.append("\n" + "\n".join(lines[start:]))
    return "\n".join(parts)
